# Generated by Django 2.1 on 2018-08-07 13:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('RR', 'Reason of Request'), ('AC', 'Account Opening'), ('WD', 'Withdrawal Issue'), ('DP', 'Deposit Issue'), ('GR', 'General Issue')], default='RR', max_length=2)),
                ('First_name', models.CharField(default=None, max_length=80)),
                ('Last_name', models.CharField(default=None, max_length=50)),
                ('Email', models.CharField(default=None, max_length=150, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('subject', models.CharField(default=None, max_length=140)),
                ('request', models.CharField(default=None, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Faq1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('Ans', models.TextField(max_length=2500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Faq',
            },
        ),
    ]
